### ISSUE TITLE
Dependencies issues with Strapi 4.10.5

### ISSUE THREAD

**Issue by OrlandoHurtadoBMC** [mattmilburn/strapi-plugin-preview-button#91] opened 2023-05-11 22:05 UTC
![dependencyError](https://github.com/mattmilburn/strapi-plugin-preview-button/assets/124398615/c783e8d1-a319-43c8-b9bd-a1ac2fae3ae7)

Hi, updating to Strapi 4.10.5 I'm having this dependency issue

**Comment by eruiz-impact** [comment] 2023-05-15 15:34
I am having the same issue.

**Comment by Qavi-Nizamani** [comment] 2023-05-17 21:57
Getting the same issue

**Comment by eruiz-impact** [comment] 2023-05-23 14:11
@mattmilburn, is there any plans to fix this?

**Comment by mattmilburn** [comment] 2023-05-23 18:14
@OrlandoHurtadoBMC @eruiz-impact @Qavi-Nizamani I am unable to reproduce this issue. Can anyone provide more details or your `package.json` contents?

The plugin requires Strapi `^4.5.6` (which is old) but should still resolve to the latest minor version (eg. 4.x.x).

**Comment by Qavi-Nizamani** [comment] 2023-05-24 21:54
> @OrlandoHurtadoBMC @eruiz-impact @Qavi-Nizamani I am unable to reproduce this issue. Can anyone provide more details or your `package.json` contents?
> 
> The plugin requires Strapi `^4.5.6` (which is old) but should still resolve to the latest minor version (eg. 4.x.x).

Have you used npm?

**Comment by zrothauser** [comment] 2023-05-26 21:01
I was having this problem with Strapi 4.10.5, and have not been able to test with 4.10.6 yet - but it looks like it may be resolved there because of a downgrade. I think the conflict was that in `helper-plugin` version 4.10.5 they updated the React dependency to use `^18`, which conflicted with React `^17.0.2` here. 

Here's the commit that reverted that back to `^17.0.2` before Strapi 4.10.6 was released:
https://github.com/strapi/strapi/pull/16793/files

**Comment by llantenv** [comment] 2023-05-30 16:29
Hi!
I tested with the latest version of Strapi (4.10.6) and the latest version of the Plugin (1.1.3) 
...but I didn't get the result I expected either.
I also use v18.15.0 of Nodejs.

I even tried starting a new instance of Strapi and just adding this plugin... and I didn't get a correct installation either.

![Captura de pantalla 2023-05-30 a la(s) 12 23 05](https://github.com/mattmilburn/strapi-plugin-preview-button/assets/51178546/79f9b058-2521-46c7-8e6b-189f6a81000d)

**Comment by Prabhanshu1808** [comment] 2023-06-01 07:03
Hi!
I tested with the latest version of Strapi (4.10.6) and the latest version of the Plugin
...but I get the error.
I use v18.16.0 of Nodejs.
![Screenshot from 2023-06-01 12-28-26](https://github.com/mattmilburn/strapi-plugin-preview-button/assets/93477549/a1afb25e-c437-4238-b860-20899a46d844)

**Comment by Zharkan** [comment] 2023-06-02 19:11
It still works with yarn though

**Comment by StrapiBartosh** [comment] 2023-06-07 19:37
I just tried installing on Strapi 4.11, which was released earlier today. I was able to get it running with no issue. I tried it using two instances of Strapi, one with yarn and one with npm, and both have no issues.

**Comment by mattmilburn** [comment] 2023-06-08 01:03
Hey all - This issue certainly seems to be resolved in Strapi's latest version 4.11.0 that released today.

You may need to also upgrade the design system to v1.8.0.

**Closed** 2023-07-12 22:46 UTC
